---
title: "LFM Analysis"
output: html_document
date: "2022-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(readxl)
library(ggplot2)
library(PairedData)
```

Load the test data set that includes 4 ppts:
```{r}
testData <- read_excel("testData.xlsx") %>% 
  mutate(condition = replace(condition, condition == 1, "error")) %>% 
  mutate(condition = replace(condition, condition == 2, "study")) 

```

Summarize Group Performance:
```{r message=FALSE, warning=FALSE}
timeOut <- testData %>% 
  filter(phase == "learn") %>% 
  filter(correct == 3) %>% 
  group_by(participant) %>% 
  summarize(
    count = n()
  )

# Remove the points in which ppt guessed correctly
study_cond <- testData %>% 
  filter(condition == "study")
wrong_guess <- testData %>% 
  filter(phase == "learn") %>% 
  filter(correct != 1) %>% 
  dplyr::select(participant, cue)

clean_test <- left_join(wrong_guess, testData, by = c("participant", "cue")) %>% 
  filter(phase == "test") %>% 
  full_join(study_cond)

indivLFM <- testData %>% 
  filter(phase == "test") %>% 
  filter(correct == 1) %>% 
  group_by(participant, condition) %>%
  summarize(
    performance = n()/30,
    avgRT = mean(rt)
  )

indivLFM_clean <- clean_test %>% 
  filter(phase == "test") %>% 
  filter(correct == 1) %>% 
  group_by(participant, condition) %>%
  summarize(
    performance = n()/30,
    avgRT = mean(rt)
  )

groupLFM <- indivLFM %>% 
  group_by(condition) %>% 
  summarize(
    meanPerformance = mean(performance),
    stdPerformance = sd(performance),
    meanRT = mean(avgRT),
    stdRT = sd(avgRT)
  )

groupLFM_clean <- indivLFM_clean %>% 
  group_by(condition) %>% 
  summarize(
    meanPerformance = mean(performance),
    stdPerformance = sd(performance),
    meanRT = mean(avgRT),
    stdRT = sd(avgRT)
  )
```

Plot something:
```{r}
ggplot(data = indivLFM) +
  geom_point(mapping = aes(x = condition, y = performance, color = participant)) +
  geom_line(mapping = aes(x = condition, y = performance, group = participant)) +
  labs(
    title = "Performance Compared by Condition",
    x = "Condition",
    y = "Performance"
  )
```

Checkout real data same way:
```{r}
# take out ppt 1066 bc timeout > 15
lfmData <- read_excel("lfmData.xlsx")

```

```{r}
timeOut <- lfmData %>% 
  filter(phase == "learn") %>% 
  filter(correct == 3) %>% 
  group_by(participant) %>% 
  summarize(
    count = n()
  )
# 1017 & 1061 ?? 

# need to remove where learn was correct
# can also do analysis where all timeout trials are taken out**

studyItems <- lfmData %>% 
  filter(condition == 2)

correct_guess <- lfmData %>% 
  filter(phase == "learn") %>% 
  filter(correct == 1) %>% 
  dplyr::select(participant, cue)

guess <- lfmData %>% 
  filter(phase == "learn") %>% 
  filter(correct != 1) %>% 
  dplyr::select(participant, cue)

cleanLFM <- left_join(guess, lfmData, by = c("participant", "cue")) %>% 
  filter(phase == "test") %>% 
  full_join(studyItems, by = c("participant", "cue", "phase", "condition", "target", "response", "rt", "correct", "Column1", "Column2"))

# sanity check: guess + timeout + correct_guess = test LFM data condition 1
check = lfmData %>% 
  filter(phase == "test") %>%
  filter(condition == 1)
checka = lfmData %>% 
  filter(phase == "learn")
check1 = lfmData %>% 
  filter(phase == "test") %>% 
  filter(condition == 1)

#cleanLFM should be size of test LFM data minus the size of correct_guess and timeout
check2 = lfmData %>% 
  filter(phase == "test")
# pass: 3720 - 66 - 232 = 3422 

LFM <- lfmData %>% 
  filter(phase == "test") %>% 
  filter(correct == 1) %>% 
  group_by(participant, condition) %>%
  summarize(
    performance = n()/30,
    avgRT = mean(rt)
  )

clean_lfm <- cleanLFM %>% 
  filter(phase == "test") %>% 
  filter(correct == 1) %>% 
  group_by(participant, condition) %>%
  summarize(
    performance = n()/30,
    avgRT = mean(rt)
  ) %>% 
  mutate(condition = replace(condition, condition == 1, "error")) %>% 
  mutate(condition = replace(condition, condition == 2, "study")) 

group <- LFM %>% 
  group_by(condition) %>% 
  summarize(
    meanPerformance = mean(performance),
    stdPerformance = sd(performance),
    meanRT = mean(avgRT),
    stdRT = sd(avgRT)
  )

clean_group <- clean_lfm %>% 
  group_by(condition) %>% 
  summarize(
    meanPerformance = mean(performance),
    stdPerformance = sd(performance),
    meanRT = mean(avgRT),
    stdRT = sd(avgRT)
  ) %>% 
  mutate(condition = replace(condition, condition == 1, "error")) %>% 
  mutate(condition = replace(condition, condition == 2, "study")) 
```

Plot something:
```{r}
ggplot(data = clean_lfm) +
  geom_point(mapping = aes(x = condition, y = performance, color = participant)) +
  geom_line(mapping = aes(x = condition, y = performance, group = participant)) +
  labs(
    title = "Performance Compared by Condition",
    x = "Condition",
    y = "Performance"
  )
```

Calculate slope:
```{r}
calc_sign <- function(numbers) {
  slope = c()
  for (i in 1:length(numbers)) {
    if (numbers[i] < 0) {
    slope[i] = "negative"
  } else if (numbers[i] > 0) {
    slope[i] = "positive"
  } else {
        slope[i] = "zero"
      }
  }
  return(slope)
}


slopeData <- clean_lfm %>% 
  group_by(participant) %>% 
  mutate(difference = diff(performance)) %>% 
  mutate(slope = calc_sign(difference)) 

ggplot(data = slopeData) +
  geom_point(mapping = aes(x = condition, y = performance, color = slope)) +
  geom_line(mapping = aes(x = condition, y = performance, group = participant, color = slope)) +
  labs(
    title = "Performance Compared by Condition",
    x = "Condition",
    y = "Performance"
  )

```

Make kernel density plot
```{r}
clean_study <- clean_lfm %>% 
  filter(condition == "study") %>% 
  dplyr::select(performance)
study <- clean_study$performance

clean_error <- clean_lfm %>% 
  filter(condition == "error") %>% 
  dplyr::select(performance)
error <- clean_error$performance

study_dens <- density(study)
error_dens <- density(error)

plot(study_dens, col='blue', ylim=c(0,3), main="Density Plot of Performance", xlab="Accuracy")
lines(error_dens, col='red')
legend(0.1, 2.5, legend=c("Study", "Error"), col=c("blue", "red"), lty=1, cex=0.8)

```

Start stat analyses:
```{r}
studyData <- subset(clean_lfm,  condition == "study", performance,
                 drop = TRUE)
errorData <-subset(clean_lfm,  condition == "error", performance,
                 drop = TRUE)

pd <- paired(studyData, errorData)
plot(pd, type = "profile") + theme_bw()

result <- t.test(studyData, errorData, paired =TRUE)
result
```